### ISSUE TITLE
test_bitcoin results

### ISSUE THREAD

**Issue by sipsorcery** [kobake/bitcoin-msvc#28]
Does test_bitcoin work properly for you?

After building the solution on Win10 and running test_bitcoin.exe I get some assert failures and then it appears to hang (I haven't debugged it as yet). I'm wondering if this could be related to my build environment or whether it's a common problem introduced by the msvc build?

If I build the bitcoin code using mingw and execute the test_bitcoin.exe produced by it it runs correctly with no errors.

**Comment by kobake** [comment]
Just now I've fixed some error about depending nuget libraries on #32 . Please try again if you like.
Only VS2017 is requird for this project.

**Comment by sipsorcery** [comment]
I ended up creating a Visual Studio build config for bitcoin-core that uses vcpkg for the dependencies.

I'm living in hope that one day the PR may get merged into the bitcoin-core repo https://github.com/bitcoin/bitcoin/pull/11526.
