### ISSUE TITLE
First build on VS2017 errors

### ISSUE THREAD

**Issue by replaysMike** [kobake/bitcoin-msvc#29]
After trying to build bitcoin-core for the entire day on Win10/VS2017 I finally gave up. I was excited to see this project and gave it a shot.

When building latest on Win10, VS2017 (15.2 (26430.16)) I get compat.h(35): fatal error C1083: Cannot open include file: 'sys/fcntl.h': No such file or directory. I tried changing the Windows SDK target to 10 instead of 8.1, but that produced the same error.

**Comment by replaysMike** [comment]
I had some success after installing Windows 10 SDK (it said it was already installed, and I was pretty sure it was), and compiling as x86 instead of x64. I don't know if the SDK had any impact, it may have purely been it won't compile x64 (still doesn't).

**Comment by matra774** [comment]
Same here.. x86 compiles, x64 does not. Possible reason: x64 configuration is missing WIN32 preprocessor define. (WIN32 should still be used for 64 bit compilation)

**Comment by mmartain** [comment]
Would love to know if u guys found a solution for x64 build problems

**Comment by kobake** [comment]
Just now I've fixed some error about depending nuget libraries. Please try again if you like.

I've checked only x86 building and not checked about x64.
I think x64 building is also important, so I'll tune the project for x64 if possible.

**Comment by kobake** [comment]
Sorry for leaving you guys for a long long time.

Now, VS2019 is more active rather than VS2017.
So, I just now made this project support VS2019 x86/x64 building instead of fixing VS2017 building problem on latest master branch.

If you like, please confirm it.

**Comment by matra774** [comment]
@kobake AFAIN Bitcoin SV as well as Bitcoin Core both supports building with MSVC. See
* https://github.com/bitcoin/bitcoin/tree/master/build_msvc  
* https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/build-windows.md#using-microsoft-visual-studio

**Comment by kobake** [comment]
Oh... Good changes had already appeared in recent years when I had not been able to observe them... Thank you for nice information 👍 

Though, I'll keep to maintain this repository for my hobby, of course with watching 2 projects you showed and also other repos.

**Comment by kobake** [comment]
As @matra774 said, original repos supports MSVC building for now, so please use it instead of this one if your purpose is not special.
