### ISSUE TITLE
Potential NuGet Reference Error in .vcxproj Files

### ISSUE THREAD

**Issue by supersausage007** [kobake/bitcoin-msvc#34]
Hi Team,

First off, great work on this project! When compiling in VS CE 2017, I get this NuGet error message:

Error		This project references NuGet package(s) that are missing on this computer.  ... The missing file is packages\boost.1.63.0.0\build\native\boost.targets.	_bitcoin_common	D:\dev\bitcoin\bitcoin-msvc-original-master-merge\_bitcoin_common.vcxproj	545	

Upon tracking down the configs in the <packages.config> file, and comparing those to, for example, <_bitcoin_common.vcxproj>, there seems to be a conflict: <packages.config> refrences boost.targ for 1.67, whereas all project files reference boost 1.63.

Is this a true error, or am I misunderstanding this setup? In any case, it breaks my compilation efforts.

Thanks in advance for your input!

**Comment by kobake** [comment]
Thank you for your reporting!
I'm going to try to fix this problem this saturday.

**Comment by kobake** [comment]
Fixed on #35!!!!!!! 😃

**Comment by supersausage007** [comment]
@kobake thank you very much!
